apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: todo-app

  template:
    metadata:
      labels:
        app: todo-app

    spec:
      containers:
      - name: todo-app
        image: sarahida/todo-app:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8080