apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Valeurs encodées en base64. Pour changer un mot de passe :
  # echo -n "ton_mot_de_passe" | base64
  POSTGRES_USER: dG9kb3VzZXI=       # todouser
  POSTGRES_PASSWORD: dG9kb3Bhc3MxMjM=  # todopass123
  POSTGRES_DB: dG9kb2Ri              # tododb
